/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision;

import control.ControleVisao;
import control.TCPCliente;
import domain.Mensagem;
import domain.Usuario;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 *
 * @author gudeck
 */
public class JDGChat extends javax.swing.JDialog implements Runnable {

    private final ControleVisao controladorVisao;
    private Usuario usuario;

    /**
     * Creates new form JDGChat
     */
    public JDGChat(java.awt.Frame parent, boolean modal,
            ControleVisao controlador, Usuario usuario) {
        super(parent, modal);
        initComponents();
        this.controladorVisao = controlador;
        this.usuario = usuario;
        this.setTitle("ID: " + usuario.getId() + ", Nome: " + usuario.getNome());
        lblErro.setVisible(false);
        txtHistorico.setEditable(false);
        new Thread(this).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMensagem = new javax.swing.JTextArea();
        lblErro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtHistorico = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mensagem");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel1, gridBagConstraints);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(btnEnviar, gridBagConstraints);

        txtMensagem.setColumns(20);
        txtMensagem.setRows(5);
        jScrollPane2.setViewportView(txtMensagem);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = 90;
        jPanel1.add(jScrollPane2, gridBagConstraints);

        lblErro.setForeground(new java.awt.Color(255, 0, 0));
        lblErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErro.setText("Escreva algo!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(lblErro, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        txtHistorico.setColumns(20);
        txtHistorico.setRows(5);
        jScrollPane3.setViewportView(txtHistorico);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 350;
        gridBagConstraints.ipady = 125;
        jPanel2.add(jScrollPane3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        List<Mensagem> mensagens;
        if (txtMensagem.getText().isEmpty())
            lblErro.setVisible(true);
        else {
            lblErro.setVisible(false);
            mensagens = TCPCliente.enviaMensagem(this.usuario, txtMensagem.getText());
            atualizaHistorico(mensagens);
            txtMensagem.setText("");
            txtMensagem.requestFocus();
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblErro;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JTextArea txtMensagem;
    // End of variables declaration//GEN-END:variables

    public void atualizaHistorico(List<Mensagem> mensagens) {
        DateTimeFormatter dtf;
        txtHistorico.setText("");
        dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        if (mensagens != null) {
            mensagens.forEach((mensagem) -> txtHistorico.append(
                    dtf.format(mensagem.getHorario()) + " "
                    + mensagem.getUsuario().getNome() + ": "
                    + mensagem.getTexto() + "\n"
            ));
        }
    }

    @Override
    public void run() {

        while (true) {
            try {
                Thread.sleep(10000);
                List<Mensagem> mensagens = TCPCliente.enviaMensagem(this.usuario, "");
                atualizaHistorico(mensagens);
            } catch (InterruptedException ex) {
                System.out.println("Erro thread: " + ex.getMessage());
            }
        }
    }
}
